apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kubeapps.apprepository.fullname" . }}
  labels:
    app: {{ template "kubeapps.apprepository.fullname" . }}
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kubeapps.apprepository-job-postupgrade.fullname" . }}
  labels:
    app: {{ template "kubeapps.apprepository.fullname" . }}
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
